name: 'Terraform Apply'

on:
  workflow_dispatch:
    inputs:
      app_id: 
        description: 'Application ID'
        required: true
      app_config:
        description: 'Application config JSON'
        required: true

env:
  TF_VAR_app_id: ${{ github.event.inputs.app_id }}
  TF_VAR_app_config: ${{ github.event.inputs.app_config }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
        role-duration-seconds: 1200
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Check and Create S3 Bucket and DynamoDB Table
      run: bash ./scripts/create_state_bucket.sh ${{ github.event.inputs.app_id }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -var-file="application.tfvars.json"

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="application.tfvars.json"